-- =============================================================================
-- V11 — 회원 알림
--   엔티티: Notification (member_id 만 저장, 연관관계 없음)
--   실시간 푸시/이메일 없음 — 지원 결과·시설 승인·문의 답변 시점에 서버가 행을 쌓고
--   프론트가 폴링으로 안읽음 배지/목록을 그리는 MVP 수준.
-- =============================================================================

create table notification (
    id bigint generated by default as identity,
    member_id bigint not null,
    type varchar(30) not null check (type in
        ('APPLICATION_ACCEPTED','APPLICATION_REJECTED','FACILITY_APPROVED','FACILITY_REJECTED','INQUIRY_ANSWERED')),
    message varchar(300) not null,
    link varchar(200),
    is_read boolean not null default false,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create index idx_notification_member_created on notification (member_id, created_at);
create index idx_notification_member_read on notification (member_id, is_read);
