-- =============================================================================
-- V12 — 포인트 잔액 컬럼 + 포인트 충전(포트원 결제) 이력 (사후 기록)
--   엔티티: Member.point, PointCharge (PointChargeStatus: PENDING/PAID)
--   PR: feature/fe-guardian-member-point-guard (#116)
--
--   이 스키마는 #116 배포 시점(StubPointService → MemberPointService 로 교체되며
--   실잔액 컬럼이 필요해짐)에 마이그레이션 파일 없이 운영 DB(Neon)에 먼저 반영됐다.
--   그 사실을 뒤늦게 git에 기록해두는 파일이라, 이미 컬럼/테이블이 있는 환경(운영)에서도
--   안전하게 통과하도록 전부 IF NOT EXISTS 로 작성한다 — CREATE TABLE IF NOT EXISTS 는
--   테이블이 이미 있으면 내부 제약조건(unique/check) 선언까지 포함해 문장 전체를 건너뛴다.
--   member_id 의 FK 제약은 Hibernate ddl-auto=validate 가 검증하지 않는 대상이라
--   운영과의 불일치 가능성을 피하려 이번엔 추가하지 않는다(필요해지면 별도 마이그레이션으로).
-- =============================================================================

alter table member add column if not exists point bigint not null default 0;

create table if not exists point_charge (
    id bigint generated by default as identity,
    member_id bigint not null,
    payment_id varchar(64) not null,
    amount bigint not null,
    status varchar(20) not null check (status in ('PENDING','PAID')),
    completed_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id),
    constraint uk_point_charge_payment_id unique (payment_id)
);

create index if not exists idx_point_charge_member on point_charge (member_id);
