-- =============================================================================
-- V13 — 인증구직자 마크
--   자격증(Certificate)의 파일 기술검증(status)과 별개로 관리자 진위 심사 축(admin_review_*)을
--   추가하고, 경력 인증(career_verification, 텍스트만)과 마크 신청(badge_request)을 신설한다.
--   badge_request 가 관리자 승인되면 jobseeker_profile.verified_badge = true.
-- =============================================================================

alter table certificate add column admin_review_status varchar(20) not null default 'PENDING';
alter table certificate add column admin_review_reason varchar(300);
alter table certificate add column reviewed_at timestamp(6);
alter table certificate add constraint certificate_admin_review_status_check
    check (admin_review_status in ('PENDING','APPROVED','REJECTED'));

create table career_verification (
    id bigint generated by default as identity,
    jobseeker_profile_id bigint not null,
    organization_name varchar(100) not null,
    role_title varchar(100),
    start_date date not null,
    end_date date,
    description varchar(500),
    status varchar(20) not null check (status in ('PENDING','APPROVED','REJECTED')),
    reject_reason varchar(300),
    reviewed_at timestamp(6),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create index idx_career_verification_profile on career_verification (jobseeker_profile_id);

create table badge_request (
    id bigint generated by default as identity,
    jobseeker_profile_id bigint not null,
    status varchar(20) not null check (status in ('PENDING','APPROVED','REJECTED')),
    requested_at timestamp(6) not null,
    decided_at timestamp(6),
    reject_reason varchar(300),
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create index idx_badge_request_profile on badge_request (jobseeker_profile_id);

alter table jobseeker_profile add column verified_badge boolean not null default false;
alter table jobseeker_profile add column verified_badge_at timestamp(6);

-- notification.type 허용값에 신규 알림 종류 추가
alter table notification drop constraint notification_type_check;
alter table notification add constraint notification_type_check check (type in
    ('APPLICATION_ACCEPTED','APPLICATION_REJECTED','FACILITY_APPROVED','FACILITY_REJECTED','INQUIRY_ANSWERED',
     'CERTIFICATE_REVIEW_APPROVED','CERTIFICATE_REVIEW_REJECTED',
     'CAREER_VERIFICATION_APPROVED','CAREER_VERIFICATION_REJECTED',
     'BADGE_GRANTED','BADGE_REJECTED'));
