-- =============================================================================
-- CareMatch 전체 스키마 스냅샷 (PostgreSQL 방언)
--
-- ⚠️ 자동 생성 파일 — 직접 수정하지 말 것. 엔티티 변경 후 재생성:
--   cd backend && ./gradlew bootRun --args="\
--     --spring.main.web-application-type=none \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create \
--     --spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=build/schema-postgres.sql \
--     --spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect \
--     --spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false \
--     --spring.jpa.hibernate.ddl-auto=none"
--   (bootRun 은 web-application-type=none 이라 컨텍스트 기동 후 non-zero 로 종료됨 — 정상.
--    스크립트는 EntityManagerFactory 초기화 시점에 build/schema-postgres.sql 로 기록됨)
--
-- 용도: prod DB 최초 프로비저닝 시 1회 실행. 자세한 절차는 docs/MIGRATION.md 참고.
-- 생성 기준: 아래 커밋의 엔티티 상태.
--
-- 참고: faq.answer / inquiry.content / inquiry_reply.content / notice.content /
--       terms.content 5개 컬럼은 @Lob 제거(→ @Column TEXT) 반영을 위해 재생성 없이
--       oid → text 로 직접 수정함. 다음 재생성 시 동일하게 text 로 나온다.
-- =============================================================================

    create table application (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        job_posting_id bigint not null,
        job_seeker_profile_id bigint not null,
        processed_at timestamp(6),
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('APPLIED','ACCEPTED','REJECTED','CANCELED')),
        message varchar(500),
        primary key (id),
        constraint uk_application_posting_seeker unique (job_posting_id, job_seeker_profile_id)
    );

    create table certificate (
        created_at timestamp(6) not null,
        file_size bigint,
        id bigint generated by default as identity,
        jobseeker_profile_id bigint not null,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('PENDING','VERIFIED','REJECTED')),
        certificate_name varchar(100) not null,
        certificate_number varchar(100),
        content_type varchar(100),
        file_key varchar(300) not null,
        reject_reason varchar(300),
        primary key (id)
    );

    create table contact_unlock_history (
        points_spent integer not null,
        facility_member_id bigint not null,
        id bigint generated by default as identity,
        jobseeker_profile_id bigint not null,
        unlocked_at timestamp(6) not null,
        primary key (id),
        constraint uk_unlock_viewer_target unique (facility_member_id, jobseeker_profile_id)
    );

    create table facility_profile (
        approved_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null unique,
        updated_at timestamp(6) not null,
        approval_status varchar(20) not null check (approval_status in ('PENDING','APPROVED','REJECTED')),
        business_registration_number varchar(20) not null,
        facility_name varchar(100) not null,
        business_license_file_key varchar(300),
        reject_reason varchar(300),
        primary key (id),
        constraint uk_facility_biz_no unique (business_registration_number)
    );

    create table faq (
        sort_order integer not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        category varchar(50) not null,
        question varchar(300) not null,
        answer text not null,
        primary key (id)
    );

    create table inquiry (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint,
        updated_at timestamp(6) not null,
        status varchar(20) not null check (status in ('PENDING','ANSWERED')),
        guest_password_hash varchar(100),
        guest_email varchar(150),
        title varchar(200) not null,
        attachment_file_key varchar(300),
        content text not null,
        primary key (id)
    );

    create table inquiry_reply (
        answered_by bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        inquiry_id bigint not null,
        content text not null,
        primary key (id)
    );

    create table job_posting (
        deadline date not null,
        exposure_priority integer not null,
        latitude float(53),
        longitude float(53),
        pay_amount integer not null,
        recruit_count integer not null,
        work_end_time time(6) not null,
        work_start_time time(6) not null,
        created_at timestamp(6) not null,
        exposure_expired_at timestamp(6),
        facility_profile_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        view_count bigint not null,
        elder_gender varchar(10) not null check (elder_gender in ('MALE','FEMALE')),
        care_grade varchar(20) not null check (care_grade in ('GRADE_1','GRADE_2','GRADE_3','GRADE_4','GRADE_5')),
        cognitive_status varchar(20) not null check (cognitive_status in ('NORMAL','MILD','SEVERE')),
        elder_age_range varchar(20),
        employment_type varchar(20) not null check (employment_type in ('FULL_TIME','CONTRACT','TEMPORARY','PART_TIME')),
        exposure_type varchar(20) not null check (exposure_type in ('NORMAL','PREMIUM','SPECIAL')),
        job_type varchar(20) not null check (job_type in ('CAREGIVER','NURSING_ASSISTANT','HOUSEKEEPER','LIFE_SUPPORT','ETC')),
        meal_status varchar(20) not null check (meal_status in ('SELF','ASSIST','TUBE')),
        mobility_status varchar(20) not null check (mobility_status in ('INDEPENDENT','PARTIAL_ASSIST','BEDRIDDEN')),
        pay_type varchar(20) not null check (pay_type in ('HOURLY','DAILY','MONTHLY')),
        status varchar(20) not null check (status in ('OPEN','CLOSED')),
        work_type varchar(20) not null check (work_type in ('COMMUTE','LIVE_IN','REMOTE','NEGOTIABLE')),
        sido varchar(30) not null,
        sigungu varchar(30) not null,
        title varchar(100) not null,
        work_days varchar(100) not null,
        address_detail varchar(200),
        employment_type_note varchar(200),
        duties varchar(500),
        required_documents varchar(500),
        thumbnail_url varchar(500),
        description TEXT,
        elder_note TEXT,
        preferred_note TEXT,
        primary key (id)
    );

    create table job_posting_draft (
        created_at timestamp(6) not null,
        facility_profile_id bigint not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        title varchar(100),
        form_json TEXT,
        primary key (id)
    );

    create table job_posting_scrap (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        job_posting_id bigint not null,
        member_id bigint not null,
        updated_at timestamp(6) not null,
        primary key (id),
        constraint uk_scrap_member_posting unique (member_id, job_posting_id)
    );

    create table jobseeker_available_task (
        jobseeker_profile_id bigint not null,
        task varchar(30) not null check (task in ('DAILY_LIFE_SUPPORT','MEAL_SUPPORT','BATH_SUPPORT','MOBILITY_SUPPORT','COGNITIVE_ACTIVITY','PERSONAL_HYGIENE','HOUSEWORK','HOSPITAL_ESCORT')),
        primary key (jobseeker_profile_id, task)
    );

    create table jobseeker_desired_employment_type (
        jobseeker_profile_id bigint not null,
        employment_type varchar(20) not null check (employment_type in ('FULL_TIME','CONTRACT','TEMPORARY','PART_TIME')),
        primary key (jobseeker_profile_id, employment_type)
    );

    create table jobseeker_profile (
        birth_year integer,
        career_years integer,
        desired_min_pay integer,
        desired_work_end_time time(6),
        desired_work_start_time time(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null unique,
        updated_at timestamp(6) not null,
        gender varchar(10) check (gender in ('MALE','FEMALE')),
        desired_job_type varchar(20) check (desired_job_type in ('CAREGIVER','NURSING_ASSISTANT','HOUSEKEEPER','LIFE_SUPPORT','ETC')),
        desired_pay_type varchar(20) check (desired_pay_type in ('HOURLY','DAILY','MONTHLY')),
        desired_work_type varchar(20) check (desired_work_type in ('COMMUTE','LIVE_IN','REMOTE','NEGOTIABLE')),
        education varchar(20) check (education in ('MIDDLE_SCHOOL','HIGH_SCHOOL','ASSOCIATE','BACHELOR','GRADUATE')),
        employment_status varchar(20) not null check (employment_status in ('SEEKING','EMPLOYED')),
        desired_sido varchar(30),
        desired_sigungu varchar(30),
        desired_work_days varchar(100),
        headline varchar(100),
        residence varchar(200),
        photo_url varchar(500),
        introduction varchar(1000),
        primary key (id)
    );

    create table member (
        login_fail_count integer not null,
        verified boolean not null,
        account_locked_until timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        membership_type varchar(20) not null,
        phone varchar(20),
        role varchar(20) check (role in ('JOBSEEKER','FACILITY','ADMIN')),
        status varchar(20) not null check (status in ('ACTIVE','SUSPENDED','WITHDRAWN')),
        login_id varchar(50),
        name varchar(50) not null,
        password varchar(100),
        email varchar(150) not null,
        primary key (id),
        constraint uk_member_login_id unique (login_id),
        constraint uk_member_email unique (email)
    );

    create table notice (
        pinned boolean not null,
        author_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        view_count bigint not null,
        title varchar(200) not null,
        content text not null,
        primary key (id)
    );

    create table refresh_token (
        revoked boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        token_hash varchar(100) not null,
        primary key (id),
        constraint uk_refresh_token_hash unique (token_hash)
    );

    create table social_account (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        updated_at timestamp(6) not null,
        provider varchar(20) not null check (provider in ('NAVER','KAKAO','GOOGLE')),
        provider_user_id varchar(100) not null,
        primary key (id),
        constraint uk_social_provider_uid unique (provider, provider_user_id)
    );

    create table terms (
        active boolean not null,
        required boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        type varchar(20) not null check (type in ('SERVICE','PRIVACY','MARKETING')),
        version varchar(30) not null,
        title varchar(200) not null,
        content text not null,
        primary key (id),
        constraint uk_terms_type_version unique (type, version)
    );

    create table terms_agreement (
        agreed boolean not null,
        agreed_at timestamp(6) not null,
        id bigint generated by default as identity,
        member_id bigint not null,
        terms_type varchar(20) not null check (terms_type in ('SERVICE','PRIVACY','MARKETING')),
        terms_version varchar(30) not null,
        primary key (id)
    );

    create table verification_code (
        attempt_count integer not null,
        verified boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6) not null,
        channel varchar(10) not null check (channel in ('EMAIL','PHONE')),
        code varchar(10) not null,
        target varchar(150) not null,
        primary key (id)
    );

    create index idx_application_posting_status 
       on application (job_posting_id, status);

    create index idx_application_seeker_status 
       on application (job_seeker_profile_id, status);

    create index idx_inquiry_member 
       on inquiry (member_id);

    create index idx_inquiry_status 
       on inquiry (status);

    create index idx_job_posting_status_region 
       on job_posting (status, sigungu, job_type);

    create index idx_job_posting_deadline 
       on job_posting (deadline);

    create index idx_job_posting_draft_facility 
       on job_posting_draft (facility_profile_id);

    create index idx_refresh_token_member 
       on refresh_token (member_id);

    create index idx_terms_agreement_member 
       on terms_agreement (member_id, terms_type);

    create index idx_verification_target 
       on verification_code (channel, target);

    alter table if exists application 
       add constraint FKtik35v4x0cxa4j8xngfdfjodh 
       foreign key (job_posting_id) 
       references job_posting;

    alter table if exists application 
       add constraint FK778e24a1fxqofekgk7gtqcy7b 
       foreign key (job_seeker_profile_id) 
       references jobseeker_profile;

    alter table if exists certificate 
       add constraint FKmmomdr763a78uh9yt4p3nmq90 
       foreign key (jobseeker_profile_id) 
       references jobseeker_profile;

    alter table if exists contact_unlock_history 
       add constraint FKmmw9e2u7his1l6l0g9wb2b1hi 
       foreign key (facility_member_id) 
       references member;

    alter table if exists contact_unlock_history 
       add constraint FKnst01vluxduwjnqom4cvx30qy 
       foreign key (jobseeker_profile_id) 
       references jobseeker_profile;

    alter table if exists facility_profile 
       add constraint FKg6rrny3qj4t8ernnd96ec1xt6 
       foreign key (member_id) 
       references member;

    alter table if exists inquiry_reply 
       add constraint FKlswrro8h5dy5y2ba8q9useih7 
       foreign key (inquiry_id) 
       references inquiry;

    alter table if exists job_posting 
       add constraint FKpjac9b2qcn1sipf8swkn082fw 
       foreign key (facility_profile_id) 
       references facility_profile;

    alter table if exists job_posting_draft 
       add constraint FK9r467dntxc37brps21ke95tp7 
       foreign key (facility_profile_id) 
       references facility_profile;

    alter table if exists job_posting_scrap 
       add constraint FKny971nmno7dweb9g01642evl7 
       foreign key (job_posting_id) 
       references job_posting;

    alter table if exists job_posting_scrap 
       add constraint FKe0vkwt5duxllyjhiijddftgx4 
       foreign key (member_id) 
       references member;

    alter table if exists jobseeker_available_task 
       add constraint FK7wvli3uk1mm52bq95qmhadkcc 
       foreign key (jobseeker_profile_id) 
       references jobseeker_profile;

    alter table if exists jobseeker_desired_employment_type 
       add constraint FK1c8bgclhjrkr16r2hrk750bkr 
       foreign key (jobseeker_profile_id) 
       references jobseeker_profile;

    alter table if exists jobseeker_profile 
       add constraint FKkgdthwolpj5c2aep2w5knfurv 
       foreign key (member_id) 
       references member;

    alter table if exists social_account 
       add constraint FK2bhcb0uq2buq7m4c6ogvo1fx8 
       foreign key (member_id) 
       references member;

    alter table if exists terms_agreement 
       add constraint FKdp4s95no40g50vnrq35stwnoh 
       foreign key (member_id) 
       references member;
